const $=s=>document.querySelector(s);let token=localStorage.getItem('ll_admin_token');let me=null;let permissions=[];
async function api(path,opt={}){const r=await fetch('/api'+path,{...opt,headers:{'Content-Type':'application/json',Authorization:token?'Bearer '+token:''}});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.message||'Request failed');return j.data||j}
function toast(m){const e=$('#toast');e.textContent=m;e.style.display='block';setTimeout(()=>e.style.display='none',2500)}
function setView(logged){$('#loginView').hidden=logged;$('#portal').hidden=!logged}
function perms(){try{return JSON.parse(me.permissions||'[]')}catch{return[]}}
function allowed(p){return me?.role==='ADMIN'||perms().includes(p)}
function nav(){const n=$('#sideNav');n.innerHTML='';[['dashboard.view','📊 Dashboard','dashboard'],['customers.view','👥 Customers','customers'],['drivers.view','🚛 Drivers','drivers'],['loads.view','📦 Loads','loads'],['bookings.view','🤝 Bookings','bookings'],['commission.verify','💰 Commission','commission'],['payments.verify','💳 Payments','payments'],['trips.view','📍 Trips','trips'],['reports.view','📈 Reports','reports']].forEach(([p,t,id])=>{if(allowed(p)){const b=document.createElement('button');b.textContent=t;b.dataset.section=id;b.onclick=()=>showPlaceholder(t);n.appendChild(b)}});if(me?.role==='ADMIN'){const b=document.createElement('button');b.textContent='👨‍💼 Managers';b.onclick=()=>showSection('managers');n.appendChild(b)}}
function showSection(s){document.querySelectorAll('.section').forEach(x=>x.hidden=true);$('#'+s+'Section').hidden=false;$('#pageTitle').textContent=s[0].toUpperCase()+s.slice(1);if(s==='managers')loadManagers()}
function showPlaceholder(t){showSection('dashboard');$('#pageTitle').textContent=t;toast('Section foundation ready — next module attach hoga.')}
async function loadDashboard(){try{const d=await api('/admin/dashboard');const data=d;$('#stats').innerHTML=Object.entries(data).map(([k,v])=>'<div class="stat"><span>'+k.replace(/([A-Z])/g,' $1')+'</span><b>'+v+'</b></div>').join('')}catch(e){toast(e.message)}}
async function loadPermissions(){const d=await api('/admin/permissions');permissions=d.permissions||[];$('#permissionInfo').innerHTML=permissions.map(p=>'<span class="tag">'+p+'</span>').join('')}
async function loadManagers(){const d=await api('/admin/managers');const ms=d.managers||[];$('#managerList').innerHTML=ms.length?ms.map(m=>'<div class="manager-row"><div><b>'+m.fullName+'</b><br><small>'+m.email+' · '+m.mobile+'</small></div><div><span class="pill">'+m.status+'</span></div><div class="tags">'+(m.permissions||[]).map(p=>'<span class="tag">'+p+'</span>').join('')+'</div><div><button class="primary" onclick="editManager(\\''+m.id+'\\')">Edit</button> <button class="primary" style="background:#b42318" onclick="toggleManager(\\''+m.id+'\\',\\''+m.status+'\\')">'+(m.status==='ACTIVE'?'Suspend':'Activate')+'</button></div></div>').join(''):'<p class="muted">No managers yet.</p>';window.__managers=ms}
async function toggleManager(id,status){try{await api('/admin/managers/'+id,{method:'PATCH',body:JSON.stringify({status:status==='ACTIVE'?'SUSPENDED':'ACTIVE'})});toast(status==='ACTIVE'?'Manager suspended':'Manager activated');loadManagers()}catch(e){toast(e.message)}}
function openManager(m){$('#managerModal').hidden=false;$('#managerId').value=m?.id||'';$('#managerModalTitle').textContent=m?'Edit Manager':'Create Manager';$('#managerName').value=m?.fullName||'';$('#managerEmail').value=m?.email||'';$('#managerMobile').value=m?.mobile||'';$('#managerEmail').disabled=!!m;$('#managerMobile').disabled=!!m;$('#managerPassword').required=!m;$('#managerPassword').value='';$('#permissionChecks').innerHTML=permissions.map(p=>'<label><input type="checkbox" value="'+p+'" '+((m?.permissions||[]).includes(p)?'checked':'')+'>'+p+'</label>').join('')}
function editManager(id){openManager(window.__managers.find(x=>x.id===id))}
$('#newManagerBtn').onclick=()=>openManager(null);$('#closeManager').onclick=()=>$('#managerModal').hidden=true;
$('#managerForm').onsubmit=async e=>{e.preventDefault();const id=$('#managerId').value;const ps=[...document.querySelectorAll('#permissionChecks input:checked')].map(x=>x.value);const body={fullName:$('#managerName').value,permissions:ps};if(!id){Object.assign(body,{email:$('#managerEmail').value,mobile:$('#managerMobile').value,password:$('#managerPassword').value})}else if($('#managerPassword').value)body.password=$('#managerPassword').value;try{await api('/admin/managers'+(id?'/'+id:''),{method:id?'PATCH':'POST',body:JSON.stringify(body)});toast('Manager saved');$('#managerModal').hidden=true;loadManagers()}catch(e){toast(e.message)}}
$('#loginForm').onsubmit=async e=>{e.preventDefault();$('#loginError').textContent='';try{const identifier=$('#loginId').value.trim();const loginBody=identifier.includes('@')?{email:identifier,password:$('#loginPassword').value}:{mobile:identifier.replace(/\s+/g,''),password:$('#loginPassword').value};const d=await api('/auth/login',{method:'POST',body:JSON.stringify(loginBody)});if(!['ADMIN','MANAGER'].includes(d.user.role))throw new Error('Admin portal sirf team accounts ke liye hai');token=d.token;me=d.user;localStorage.setItem('ll_admin_token',token);setView(true);$('#identity').innerHTML='<b>'+me.fullName+'</b><br><small>'+me.role+'</small>';$('#roleText').textContent=me.role==='ADMIN'?'Full system access':'Permission based access';$('#statusPill').textContent=me.status;nav();if(me.role==='ADMIN'){loadPermissions();loadDashboard();}else{permissions=perms();if(allowed('dashboard.view'))loadDashboard();} }catch(e){$('#loginError').textContent=e.message}}
$('#logoutBtn').onclick=()=>{localStorage.removeItem('ll_admin_token');token=null;me=null;setView(false)}
(async()=>{if(!token){setView(false);return}try{const d=await api('/auth/me');me=d.user||d;setView(true);$('#identity').innerHTML='<b>'+me.fullName+'</b><br><small>'+me.role+'</small>';$('#roleText').textContent=me.role==='ADMIN'?'Full system access':'Permission based access';$('#statusPill').textContent=me.status;nav();if(me.role==='ADMIN'||allowed('dashboard.view'))loadDashboard()}catch(e){localStorage.removeItem('ll_admin_token');token=null;setView(false)}})();