services:
  - type: web
    name: loadlink-pakistan
    runtime: node
    buildCommand: npm install && npx prisma generate --schema=./schema.prisma
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        sync: false
